name: Petty
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  
targets:
  Petty:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Petty
        excludes:
          - "*.plist"
    resources:
      - Petty/Assets.xcassets
      - Petty/Preview Content
    info:
      path: Petty/Info.plist
      properties:
        CFBundleDisplayName: Petty
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.petty
      DEVELOPMENT_TEAM: "" # Users should set their own team ID
      SWIFT_VERSION: "5.0"
      TARGETED_DEVICE_FAMILY: "1,2"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      ENABLE_PREVIEWS: true 